{% set version = "0.15.3" %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: bat
  version: {{ version }}

source:
  url: https://github.com/sharkdp/bat/archive/v{{ version }}.tar.gz
  sha256: 5880d3c25a964991ae573f3059b432c13f7e97530e2e28aa25ec2d4a06f6b926

build:
  number: 0

requirements:
  build:
    - rust
    - {{ compiler('c') }}              # [unix]
    - {{ compiler('m2w64_c') }}        # [win]
  host:
    - clangdev              # [not osx]
    - llvmdev               # [not osx]

test:
  commands:
    - bat --help

about:
  home: https://github.com/sharkdp/bat
  license: MIT
  license_family: MIT
  summary: A cat(1) clone with syntax highlighting and Git integration
  license_file: LICENSE-MIT

extra:
  recipe-maintainers:
    - apcamargo
    - dbast
