{% set version = "0.12.1" %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: bat
  version: {{ version }}

source:
  url: https://github.com/sharkdp/bat/archive/v{{ version }}.tar.gz
  sha256: 1dd184ddc9e5228ba94d19afc0b8b440bfc1819fef8133fe331e2c0ec9e3f8e2

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - rust
    - {{ compiler('c') }}              # [unix]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{native}}binutils
  host:
    - clangdev              # [not osx]
    - llvmdev               # [not osx]

test:
  commands:
    - bat --help

about:
  home: https://github.com/sharkdp/bat
  license: MIT
  summary: A cat(1) clone with syntax highlighting and Git integration
  license_file: LICENSE-MIT

extra:
  recipe-maintainers:
    - apcamargo
    - dbast
